modules:
  - type: rpm-ostree
    install:
      - binutils
      - gcc
      - gcc-c++
      - g++
      - glibc
      - glibc-devel
      - openssl
      - openssl-devel
      - libpcap-devel

  - type: script
    scripts:
      - ld-symlink-workaround.sh
